spring:
  messages:
    basename: errors

  datasource:
    url: jdbc:h2:tcp://localhost/~/happyhouse
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug

server.servlet.session:
  tracking-modes: cookie
  timeout: 1800
